linestorm_cms_admin_module_media:
    pattern:  /
    defaults: { _controller: LineStormMediaBundle:Admin/Media:list }

linestorm_cms_admin_module_media_create:
    pattern:  /new
    defaults: { _controller: LineStormMediaBundle:Admin/Media:new }

linestorm_cms_admin_module_media_view:
    pattern:  /{id}
    defaults: { _controller: LineStormMediaBundle:Admin/Media:view }
    requirements:
       id: \d+

linestorm_cms_admin_module_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormMediaBundle:Admin/Media:edit }
    requirements:
       id: \d+

linestorm_cms_admin_module_media_upload_edit:
    path: /{id}/upload
    defaults: { _controller: "LineStormMediaBundle:Admin/Media:uploadEdit" }
    requirements:
       id: \d+

linestorm_cms_admin_module_media_upload:
    path: /upload
    defaults: { _controller: "LineStormMediaBundle:Admin/Media:upload" }


linestorm_cms_admin_module_media_category_edit:
    pattern:  /category/{id}/edit
    defaults: { _controller: LineStormMediaBundle:Admin/Category:edit }
    requirements:
       id: \d+
