linestorm_blog_admin_module_media:
    pattern:  /
    defaults: { _controller: LineStormMediaBundle:Admin:list }

linestorm_blog_admin_module_media_create:
    pattern:  /new
    defaults: { _controller: LineStormMediaBundle:Admin:new }

linestorm_blog_admin_module_media_view:
    pattern:  /{id}
    defaults: { _controller: LineStormMediaBundle:Admin:view }
    requirements:
       id: \d+

linestorm_blog_admin_module_media_edit:
    pattern:  /{id}/edit
    defaults: { _controller: LineStormMediaBundle:Admin:edit }
    requirements:
       id: \d+

linestorm_blog_admin_module_media_upload_edit:
    path: /{id}/upload
    defaults: { _controller: "LineStormMediaBundle:Admin:uploadEdit" }
    requirements:
       id: \d+

linestorm_blog_admin_module_media_upload:
    path: /upload
    defaults: { _controller: "LineStormMediaBundle:Admin:upload" }

