parameters:
  linestorm.cms.module.media.class:            LineStorm\MediaBundle\Module\MediaModule
  linestorm.cms.module.media.manager.class:    LineStorm\MediaBundle\Media\MediaManager

services:

  linestorm.cms.module.media:
    class: %linestorm.cms.module.media.class%
    tags:
      - { name: linestorm.cms.module }

  #
  # MEDIA MANAGER
  #
  linestorm.cms.media_manager:
        class: %linestorm.cms.module.media.manager.class%
