#
# DEFAULT FORM TYPES
#
parameters: ~

services:

  linestorm.cms.form.type.widget.mediaentity:
        class: LineStorm\MediaBundle\Form\Type\MediaEntityType
        arguments: [@linestorm.cms.media_manager]
        tags:
            - { name: form.type, alias: mediaentity }

  linestorm.cms.form.type.media:
        class: LineStorm\MediaBundle\Form\MediaFormType
        arguments: [@linestorm.cms.media_manager]
        tags:
            - { name: form.type, alias: linestorm_cms_form_media }
